### ISSUE TITLE
Proposal Form: On some of the fields, the "... Saving ..." message does not wrap properly (see screenshot)

### ISSUE THREAD

**Issue by lukeheath** [ConsensusBot/fpr-app#28]
The first few fields the message wraps properly, but the second half of the page there is no line break: 

![image](https://user-images.githubusercontent.com/2495927/35056883-c80d61de-fb78-11e7-8598-70edcd12dcc9.png)

**Comment by lukeheath** [comment]
@seanwarman I saw that the lazy modifier PR was supposed to address this, but after merging everything into `master`, it seems that the "... Saving ..." message is no longer appearing at all. As I move through the proposal form, most of the time there is no "Saving" message, which is okay, but sometimes the input description disappears briefly but no "Saving" message appears, which looks a bit odd. Are you seeing that on your end? If not, I'll try to capture it as a screen recording to demo for you.

**Comment by seanwarman** [comment]
Yes I've seen that I'll look into it.

**Comment by seanwarman** [comment]
https://github.com/ConsensusBot/gitter-gimp/pull/49
