### ISSUE TITLE
Proposal Form: Auto-save functionality is overwriting new content. 

### ISSUE THREAD

**Issue by lukeheath** [ConsensusBot/fpr-app#29]
When creating or editing a proposal, the app auto-saves progress when you blur an input element (deselect it). If you tab into another input and start typing while the form is auto-saving, you will lose your new content when the form finishes auto-saving. I'll send you a screen recording of the issue via Slack.

This may require both of us to debug, but it would be great for you to give it a shot first and try to determine what's going on and how we might fix it.

**Comment by seanwarman** [comment]
https://github.com/ConsensusBot/gitter-gimp/pull/34
