### ISSUE TITLE
Mobile: Expanded menu is misaligned

### ISSUE THREAD

**Issue by lukeheath** [ConsensusBot/fpr-app#36]
When expanded, the mobile menu items are misaligned on the right side of the page, like this: 

![image](https://user-images.githubusercontent.com/2495927/35124725-c18a4c24-fc6c-11e7-891b-7483a38b82b6.png)

It should look like the standard bootstrap mobile menu: 

![image](https://user-images.githubusercontent.com/2495927/35124765-e3d6ea8a-fc6c-11e7-8d80-855484edb826.png)

Which is available at this URL: https://getbootstrap.com/docs/4.0/examples/navbars/

The navigation items should wrap underneath the nav bar instead of aligning on the right side.

**Comment by lukeheath** [comment]
@seanwarman It looks like there may be a missing closing tag? To start, I would recommend verifying that the navbar markup is correct with all closing tags in place.

**Comment by seanwarman** [comment]
https://github.com/ConsensusBot/gitter-gimp/pull/42
