### ISSUE TITLE
Change unauthorized menu items

### ISSUE THREAD

**Issue by lukeheath** [ConsensusBot/fpr-app#37]
When a user is not logged in, change the menu items to: 

1) Login with Github
2) FAQ

And remove the other menu items, "Github" and "Chat". Also remove any files related to the "Chat" view.

![image](https://user-images.githubusercontent.com/2495927/35125442-3d569112-fc6f-11e7-8607-1c82c4751d05.png)

**Comment by seanwarman** [comment]
Need to ask about this one. I'm not sure, if i can, how to make another function to serve the address to layouts through hooks/github/index.js

Or how to serve it some other way.

**Comment by lukeheath** [comment]
@seanwarman Good question! Looking into this now.

**Comment by seanwarman** [comment]
Yeah, still can't figure this out! I've just emailed Mike McNeil about it.

**Comment by lukeheath** [comment]
Done!
