### ISSUE TITLE
If user has no listed proposals, hide the listed proposals header

### ISSUE THREAD

**Issue by lukeheath** [ConsensusBot/fpr-app#38]
![image](https://user-images.githubusercontent.com/2495927/35125557-a90c4bcc-fc6f-11e7-8b4a-bdc6a82f31c0.png)

**Comment by lukeheath** [comment]
After merging your PR into master I'm still seeing the "Pending Approvals" header with no pending approvals. Would you please take a look on your end?: 

![image](https://user-images.githubusercontent.com/2495927/35195312-3f789354-fe87-11e7-8f78-b1fafda4bc6e.png)

Overall we should think about what a blank state looks like on this screen (no saved and no pending). I'd imagine there would be no header, and instead just a CTA (call to action) button that says "Start building a proposal"

**Comment by seanwarman** [comment]
All done... https://github.com/ConsensusBot/fpr-app/pull/59
