### ISSUE TITLE
If you have a proposal with no title in "Draft" or "Pending" mode it has no text in the link from dashboard

### ISSUE THREAD

**Issue by lukeheath** [ConsensusBot/fpr-app#39]
![image](https://user-images.githubusercontent.com/2495927/35125926-013a3448-fc71-11e7-887e-e618d13bc2d3.png)

We should probably set "Title" as required in order to save the draft or submit for review.

**Comment by lukeheath** [comment]
@seanwarman Spoke with Nick, and no fields should be required to save the draft, but if there's no title we should put something as the title so that there is a link. How about "Draft Proposal"?

In order to submit a proposal, all fields should be required except "Other"

**Comment by seanwarman** [comment]
I've done this, now just working on making the fields required, turned out to be a little trickier than I thought because I can't just change the object model and need to write some js and bootstrap for it.

Will come back to this tomorrow.

**Comment by seanwarman** [comment]
Form now checks to see if all required fields are filled.

**Comment by seanwarman** [comment]
https://github.com/ConsensusBot/gitter-gimp/tree/fix/form-draft-title

**Comment by lukeheath** [comment]
@seanwarman It does, but as soon as you open the proposal page it creates a draft proposal with no title. If you go back to the dashboard without entering a title, it looks like this: 

![image](https://user-images.githubusercontent.com/2495927/35195687-eda64926-fe8c-11e7-83e9-4682395c3b8b.png)

A good solve for this could be to not save the draft on load, but instead wait until at least a title has been entered.

**Comment by seanwarman** [comment]
Ok I'll have another look

**Comment by seanwarman** [comment]
This issue should be fixed in https://github.com/ConsensusBot/fpr-app/pull/50
