### ISSUE TITLE
Form required fields text is showing markup

### ISSUE THREAD

**Issue by lukeheath** [ConsensusBot/fpr-app#62]
This is likely due to overlapping merges, but when I hit the submit button the correct required text appears and the fields highlight (looks great!) but at the bottom of the page it's showing some additional markup: 

![image](https://user-images.githubusercontent.com/2495927/35291376-bb5fe24a-0032-11e8-84c1-c23f990cd41d.png)

**Comment by seanwarman** [comment]
https://github.com/ConsensusBot/fpr-app/pull/65
