### ISSUE TITLE
On deployed instance, the /form page does not load and errors are thrown in the browser console

### ISSUE THREAD

**Issue by lukeheath** [ConsensusBot/fpr-app#68]
Console (Mac/Chrome): 

```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at ajax-form.component.js:68
    at ajax-form.component.js:201
form.page.js:71 Uncaught ReferenceError: regeneratorRuntime is not defined
    at form.page.js:71
    at form.page.js:258
form.review.js:46 Uncaught ReferenceError: regeneratorRuntime is not defined
    at form.review.js:46
    at form.review.js:105
```

![image](https://user-images.githubusercontent.com/2495927/35353374-9940cf32-010c-11e8-86c5-b0f249a23e96.png)

**Comment by lukeheath** [comment]
@seanwarman Nevermind! Nick is going to tackle this one.

**Comment by alwaysAn0n** [comment]
@lukeheath @seanwarman This appears to be fixed now.  If the problem reappears, do this then commit the change.

`rm -rf package-lock.json && rm -rf node_modules && npm install sails-hook-grunt@3 --save`

**Comment by lukeheath** [comment]
Fixed by added a `runtime-regenerator` polyfill to the front-end dependencies: https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js
